[project]
name = "triton"
version = "0.1.0"
description = "AI Agent with planning and execution"
requires-python = ">= 3.11"
dependencies = [
    "pyautogui>=0.9.54",
    "requests>=2.31.0",
    "Pillow>=10.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]